import type { PostItem } from "@/lib/admin/types";

/**
 * Her tamamlanan proje için yerel SEO / GEO odaklı blog yazıları.
 * Anahtar kelimeler: Tokat müteahhit, Tokat inşaat, Turhal inşaat, TBDY, deprem.
 */
export const projectBlogPosts: PostItem[] = [
  {
    slug: "turhal-28-daireli-konut-deprem-yonetmeligi",
    title: "Turhal’da 28 Daireli Konut: 2026 Deprem Koşullarına Uygun Müteahhitlik",
    excerpt:
      "Tokat Turhal’da MUFAT’ın proje ve müteahhitliğini yürüttüğü 28 daireli 3+1 konut binası; TBDY 2018 ve güncel yapı mevzuatına uygun şekilde tamamlandı.",
    category: "Projelerimiz",
    tags: ["Tokat müteahhit", "Turhal inşaat", "Tokat inşaat", "TBDY", "Konut", "Deprem"],
    date: "2026-07-12",
    readMin: 7,
    cover: "https://res.cloudinary.com/osgt7obm/image/upload/v1784190766/mufat/projects/3-1-28-daireli-konut.jpg",
    body: [
      "Tokat ve Turhal’da konut yaptırmak isteyen yatırımcıların ilk sorusu nettir: bina güncel deprem koşullarına uygun mu? MUFAT İnşaat Mühendislik olarak Turhal’da tamamladığımız 28 daireli 3+1 konut binasında cevap evettir. Yapı; 2026 itibarıyla yürürlükteki Türkiye Bina Deprem Yönetmeliği (TBDY 2018) ve ilgili imar–ruhsat mevzuatına uygun plan, proje ve müteahhitlik süreçleriyle hayata geçirilmiştir.",
      "Turhal inşaat pazarında güven veren bir Tokat müteahhit profili; yalnızca cephe estetiğiyle değil, taşıyıcı sistem hesabı, zemin etüdü ve ruhsat paketinin bütünlüğüyle oluşur. Bu projede plan/proje ile müteahhitlik tek elden yönetildi. Beyaz, antrasit ve bej tonlarındaki çağdaş cephe, cam balkon korkulukları ve zemin kat ticaret alanları; saha imalat disipliniyle birlikte teslim edildi.",
      "Deprem bölgesinde konumlanan Tokat’ta konut üretmek, yönetmelik maddelerini kağıt üzerinde bırakmamayı gerektirir. Statik çözümler, performans hedefleri ve malzeme kontrolleri; ruhsat aşamasından iskâna kadar belgelenir. 28 dairelik bu yapı, Turhal’da büyük ölçekli konut arayanlar için hem yaşam konforu hem de mühendislik güvencesi sunar.",
      "Tokat inşaat sektöründe doğru müteahhit seçimi; şantiye şefliği, kontrollük ve teslim dokümantasyonunun şeffaflığıyla ölçülür. MUFAT, Cumhuriyet Cad. merkezli ofisiyle Turhal ve Tokat genelinde aynı standartları uygular: güncel deprem yönetmeliği, yasal süreçlere tam uyum, işverenle açık iletişim.",
      "Bu projenin görselleri ve teknik özeti için proje sayfamızı inceleyebilirsiniz: /projeler/3-1-28-daireli-konut. Turhal veya Tokat’ta benzer bir konut yatırımı planlıyorsanız, keşif ve ön görüşme için bizimle iletişime geçebilirsiniz.",
    ],
  },
  {
    slug: "turhal-3-1-10-daireli-konut-tokat-muteahhit",
    title: "Turhal 3+1 10 Daireli Konut: Tokat Müteahhit Standartlarıyla Teslim",
    excerpt:
      "Turhal’da 10 daireli 3+1 konut; MUFAT müteahhitliği ve plan/proje hizmetiyle, 2026 deprem koşulları ve yasalara uygun şekilde tamamlandı.",
    category: "Projelerimiz",
    tags: ["Tokat müteahhit", "Turhal inşaat", "3+1 konut", "TBDY", "Deprem"],
    date: "2026-07-10",
    readMin: 6,
    cover: "https://res.cloudinary.com/osgt7obm/image/upload/v1784190453/mufat/projects/3-1-10-daireli-konut.jpg",
    body: [
      "Turhal inşaat piyasasında 3+1 daire talebi yüksektir; ancak alıcılar artık yalnızca metrekareye değil, deprem güvenliğine bakar. MUFAT’ın Turhal’da tamamladığı beş katlı, 10 daireli 3+1 konut binası; 2026’da geçerli deprem yönetmeliği (TBDY 2018) ve yapı ruhsatı süreçlerine uygun mühendislik ve müteahhitlik anlayışıyla üretildi.",
      "Tokat müteahhit arayan işverenler için kritik fark, projenin sahaya birebir yansımasıdır. Bu yapıda açık zemin kat, geniş balkonlar ve renkli yatay cephe panelleri; plan/proje koordinasyonu altında imal edildi. Estetik kararlar, taşıyıcı sistem ve mevzuat kısıtlarından bağımsız düşünülmedi.",
      "Tokat inşaat ve Turhal konut yatırımlarında ruhsat, iskan ve teknik belgeler zinciri eksiksiz olmalıdır. MUFAT bu zinciri tek ofisten yönetir: zemin etüdünden statik projeye, şantiye uygulamasından teslime kadar aynı mühendislik dili kullanılır.",
      "10 dairelik ölçek; hem bireysel yatırımcı hem küçük kooperatif modelleri için yönetilebilir bir tipolojidir. Güncel deprem koşullarına uygun tasarım ve imalat, uzun vadede satış ve kira değerini de korur.",
      "Proje detayı: /projeler/3-1-10-daireli-konut. Tokat veya Turhal’da benzer bir 3+1 konut planlıyorsanız MUFAT ile ön görüşme yapabilirsiniz.",
    ],
  },
  {
    slug: "turhal-2-0-10-daireli-modern-konut",
    title: "Turhal’da Modern 2+0 Konut: Depreme Dayanıklı Tokat İnşaat Örneği",
    excerpt:
      "10 daireli 2+0 konut binası; Turhal’da MUFAT proje ve müteahhitliğiyle, güncel deprem koşulları ve yasalara uygun tamamlandı.",
    category: "Projelerimiz",
    tags: ["Turhal inşaat", "Tokat inşaat", "2+0 konut", "Deprem", "Müteahhit"],
    date: "2026-07-08",
    readMin: 6,
    cover: "https://res.cloudinary.com/osgt7obm/image/upload/mufat/projects/2-0-10-daireli-konut",
    body: [
      "Genç aileler ve yatırımcılar için 2+0 daireler Turhal’da hızlı talep görür. MUFAT İnşaat Mühendislik, 10 daireli 2+0 konut binasını modern cephe diliyle birlikte; 2026 itibarıyla geçerli deprem yönetmeliği ve imar mevzuatına uygun şekilde planlayıp inşa etti.",
      "Tokat inşaat sektöründe “modern görünüm” tek başına yeterli değildir. Ahşap dokulu düşey cephe, geniş balkonlar ve cam korkuluklar; taşıyıcı sistem ve yangın–kaçak güvenliği kurallarıyla birlikte çözülmelidir. Bu projede plan/proje ile müteahhitlik aynı çatı altında yürütüldü.",
      "Tokat müteahhit seçerken işverenin bakması gerekenler: ruhsat dosyasının bütünlüğü, şantiye kontrolleri ve teslim sonrası dokümantasyon. MUFAT, Turhal merkezli ekibiyle bu süreçleri şeffaf yönetir.",
      "Deprem riski yüksek bölgelerde küçük metrekareli daireler de aynı mühendislik ciddiyetini hak eder. Güncel TBDY çerçevesinde üretilen bu yapı, Turhal’da güvenli ve çağdaş bir yaşam seçeneği sunar.",
      "Görseller ve özet: /projeler/2-0-10-daireli-konut. Turhal veya Tokat’ta 2+0 konut yatırımı için iletişime geçin.",
    ],
  },
  {
    slug: "furkan-apartmani-turhal-deprem-guvenli-konut",
    title: "Furkan Apartmanı Turhal: Deprem Güvenli 3+1 Konut Müteahhitliği",
    excerpt:
      "Turhal Furkan Apartmanı; 10 daireli 3+1 konut olarak MUFAT müteahhitliğiyle, güncel deprem koşulları ve yasalara uygun teslim edildi.",
    category: "Projelerimiz",
    tags: ["Furkan Apartmanı", "Turhal inşaat", "Tokat müteahhit", "Deprem", "Konut"],
    date: "2026-07-06",
    readMin: 6,
    cover: "https://res.cloudinary.com/osgt7obm/image/upload/mufat/projects/furkan-apartmani",
    body: [
      "Furkan Apartmanı, Turhal’da MUFAT’ın plan/proje ve müteahhitliğini üstlendiği 10 daireli 3+1 konut binasıdır. Yapı; 2023 teslimiyle birlikte, firmanın 2026’da da savunduğu çizgiyi yansıtır: yürürlükteki deprem yönetmeliği, ruhsat mevzuatı ve şantiye disiplinine tam uyum.",
      "Tokat müteahhit arayanlar için referans yapı, satış katalogundan önce taşıyıcı sistem ve uygulama kalitesidir. Ahşap dokulu cephe panelleri, cam balkonlar ve modern dış aydınlatma; Furkan Apartmanı’nda mühendislik kararlarının üzerine inşa edilen mimari dilin parçasıdır.",
      "Turhal inşaat ekosisteminde güven, tekrarlayan işveren ilişkisiyle ölçülür. MUFAT; Tokat genelinde konut, eğitim ve endüstriyel yapılarda biriktirdiği deneyimi her yeni şantiyeye taşır.",
      "Güncel deprem koşullarına uygun üretim; yalnızca yeni yönetmelik metnini okumak değil, sahada beton, donatı ve detay imalatlarını denetlemektir. Furkan Apartmanı bu yaklaşımın somut bir örneğidir.",
      "Proje sayfası: /projeler/furkan-apartmani. Turhal’da benzer bir apartman yatırımı için MUFAT ile görüşebilirsiniz.",
    ],
  },
  {
    slug: "adalet-apartmani-turhal-konut-dukkan",
    title: "Adalet Apartmanı: Turhal’da Konut + Dükkan, Yasalara Uygun İnşaat",
    excerpt:
      "Adalet Apartmanı; 10 daire 2+1 ve 2 dükkanıyla Turhal’da tamamlandı. MUFAT müteahhitliği, güncel deprem ve imar mevzuatına uygun süreçle yürüdü.",
    category: "Projelerimiz",
    tags: ["Adalet Apartmanı", "Turhal inşaat", "Tokat inşaat", "Ticari", "Deprem"],
    date: "2026-07-04",
    readMin: 6,
    cover: "https://res.cloudinary.com/osgt7obm/image/upload/v1784190536/mufat/projects/adalet-apartmani.jpg",
    body: [
      "Turhal’da cadde üstü yatırımlarda konut ile ticaretin aynı yapıda çözülmesi yaygındır. Adalet Apartmanı; 10 adet 2+1 daire ve zemin katta 2 dükkanla bu modele cevap verir. MUFAT, plan/proje ve müteahhitliği 2022’de tamamladı; yaklaşımımız bugün de aynıdır: 2026 deprem koşulları ve yasal süreçlere uygun üretim.",
      "Tokat inşaat ve Turhal müteahhitlik işlerinde karma kullanımlı yapılar; yangın, kaçış, otopark ve imar şartları açısından ekstra dikkat ister. Adalet Apartmanı’nda konut ve dükkan fonksiyonları mevzuata uygun ayrım ve detaylarla çözüldü.",
      "Depreme dayanıklı yapı demek, yalnızca kolon–kiriş hesabı demek değildir. Zemin kat ticari açıklıkları, üst kat konut rijitliğiyle dengelenmeli; bu denge TBDY çerçevesinde kurulmalıdır. MUFAT’ın Tokat müteahhit pratiği bu dengeyi sahaya taşır.",
      "Yatırımcı için sonuç: hem kiralanabilir dükkan hem güvenli konut stoku. Tokat ve Turhal’da benzer karma projeler için keşif görüşmesi sunuyoruz.",
      "Detaylar: /projeler/adalet-apartmani",
    ],
  },
  {
    slug: "uslu-tekstil-fabrika-turhal-endustriyel-insaat",
    title: "Uslu Tekstil Fabrika Binası: Turhal’da Endüstriyel İnşaat ve Deprem Disiplini",
    excerpt:
      "4.200 m² Uslu Tekstil fabrika binası; Turhal’da MUFAT ile inşa edildi. Endüstriyel yapılarda da güncel deprem ve yasal standartlar esastır.",
    category: "Projelerimiz",
    tags: ["Turhal inşaat", "Tokat inşaat", "Fabrika", "Endüstriyel", "Çelik"],
    date: "2026-07-02",
    readMin: 7,
    cover: "https://res.cloudinary.com/osgt7obm/image/upload/mufat/projects/uslu-tekstil-fabrika",
    body: [
      "Turhal ve Tokat OSB hattında fabrika yatırımı planlayan işverenler için taşıyıcı sistem ve saha düzeni kritiktir. Uslu Tekstil Fabrika Binası’nda MUFAT; 4.200 m² üretim alanını yapı iskeleti, cephe ve saha imalatlarıyla birlikte yönetti. Endüstriyel yapılarda da firmanın çizgisi nettir: yürürlükteki deprem yönetmeliği ve ilgili yasalara uygun mühendislik.",
      "Tokat inşaat sektöründe fabrika demek geniş açıklık, vinç yükleri ve hızlı montaj demektir. Bu gereksinimler, TBDY ve ilgili standartlarla çelişmeden çözülmelidir. Geniş açıklıklı üretim alanı, tesis süreçlerine uygun teslim edildi.",
      "Tokat müteahhit ve endüstriyel taahhüt arayan firmalar; ruhsat, iş güvenliği ve teknik şartname uyumunu aynı pakette görmek ister. MUFAT, Turhal merkezli deneyimiyle konuttan sanayiye aynı kontrol kültürünü uygular.",
      "2026’da yatırım yapan sanayici için “ucuza biten fabrika” değil, yönetmeliğe uygun ve işletmeye hazır tesis önemlidir. Uslu Tekstil projesi bu yaklaşımın referanslarından biridir.",
      "Proje: /projeler/uslu-tekstil-fabrika. Turhal veya Tokat’ta fabrika / OSB yapısı için iletişime geçin.",
    ],
  },
  {
    slug: "tokat-tibbi-atik-tesisi-insaat",
    title: "Tokat Tıbbi Atık Tesisi: Kamu Ölçeğinde Güvenli İnşaat",
    excerpt:
      "600 m² Tokat tıbbi atık tesisi; Turhal’da çelik iskelet ve teknik şartnameye uygun teslim. MUFAT kontrollük ve yapım disiplini.",
    category: "Projelerimiz",
    tags: ["Tokat inşaat", "Turhal inşaat", "Tıbbi atık", "Çelik", "Kamu"],
    date: "2026-06-28",
    readMin: 6,
    cover: "https://res.cloudinary.com/osgt7obm/image/upload/mufat/projects/tibbi-atik-tesisi",
    body: [
      "Kamu ve özel sektörün kesiştiği tesis yapılarında mevzuat toleransı yoktur. Tokat Tıbbi Atık Tesisi’nde MUFAT; 600 m² alanda çelik iskelet, duvar ve çatı imalatlarını tamamlayarak tesisi işletmeye hazır hale getirdi. Yaklaşımımız bugün de geçerlidir: 2026 deprem koşulları ve yasal şartnamelere uygun üretim.",
      "Tokat inşaat referansları arasında özel süreçli tesisler, firmanın mühendislik derinliğini gösterir. Tıbbi atık gibi hassas fonksiyonlarda saha koordinasyonu, teknik şartnameye birebir uyum gerektirir.",
      "Turhal’da üretilen bu tesis, Tokat genelinde çevresel altyapı yatırımlarının güvenli yapı stoğuyla desteklenmesi gerektiğini hatırlatır. Deprem yönetmeliği, endüstriyel ve özel amaçlı yapılarda da aynı ciddiyetle uygulanmalıdır.",
      "MUFAT; Tokat müteahhit ve kontrollük hizmetlerinde kamu–özel işlerde belgelenebilir süreç yönetimi sunar.",
      "Proje özeti: /projeler/tibbi-atik-tesisi",
    ],
  },
  {
    slug: "asude-apartmani-turhal-yap-sat",
    title: "Asude Apartmanı Turhal: Yap-Sat Konutta Deprem ve Mevzuat Disiplini",
    excerpt:
      "Asude Apartmanı; 10 daire ve 5 dükkanla Turhal’da tamamlandı. MUFAT yap-sat / özel bina çizgisinde yasalara ve deprem güvenliğine bağlı kaldı.",
    category: "Projelerimiz",
    tags: ["Asude Apartmanı", "Turhal inşaat", "Yap sat", "Tokat müteahhit", "Konut"],
    date: "2026-06-25",
    readMin: 6,
    cover: "https://res.cloudinary.com/osgt7obm/image/upload/mufat/projects/asude-apartmani",
    body: [
      "Asude Apartmanı, Turhal’da konut ve ticaret fonksiyonunu birleştiren 10 daire + 5 dükkanlı bir yapıdır. MUFAT’ın özel bina / yap-sat deneyiminde temel ilke değişmez: imar ve ruhsat süreçlerine uyum, deprem güvenliğini merkeze alan mühendislik.",
      "Tokat ve Turhal’da yap-sat alan alıcılar; “iskan var mı, proje ruhsatlı mı, taşıyıcı sistem belgelendi mi?” sorularını sormalıdır. Asude Apartmanı, çevre dokusuna uyumlu cephe ve balkon düzeniyle birlikte bu disiplinin ürünüdür.",
      "2026’da konuştuğumuz deprem koşulları, geçmişte üretilen portföyümüzün de aynı güvenlik kültürüyle okunmasını gerektirir. MUFAT, her yeni projede TBDY ve yürürlükteki mevzuatı güncel haliyle uygular.",
      "Tokat müteahhit arayan arsa sahipleri için yap-sat ve kat karşılığı modellerinde şeffaf sözleşme + teknik uyum kritiktir. Ofisimiz bu modellerde uçtan uca süreç yönetir.",
      "Proje: /projeler/asude-apartmani",
    ],
  },
  {
    slug: "liva-evleri-turhal-22-daireli-konut",
    title: "Liva Evleri: Turhal’da 22 Daireli Konut ve Güvenli İnşaat Anlayışı",
    excerpt:
      "Liva Evleri 22 daireyle Turhal’da teslim edildi. MUFAT’ın çok daireli konut pratiği; deprem ve yasal uyumu ön planda tutar.",
    category: "Projelerimiz",
    tags: ["Liva Evleri", "Turhal inşaat", "Tokat inşaat", "Konut", "Deprem"],
    date: "2026-06-22",
    readMin: 6,
    cover: "https://res.cloudinary.com/osgt7obm/image/upload/mufat/projects/liva-evleri",
    body: [
      "Çok daireli konutlarda kalite, tek dairenin iç mimarisinden önce şantiye yönetiminde görünür. Liva Evleri’nde 22 daire; kaba ve ince işlerin aşamalı yönetimiyle Turhal’da kullanıma hazır hale getirildi. MUFAT için ölçüt: yasal süreçlere ve deprem mühendisliği disiplinine bağlı kalmak.",
      "Tokat inşaat yatırımlarında 20+ daireli bloklar; hem finansman hem teslim planlaması ister. Turhal’daki bu proje, firmanın ölçeklenebilir müteahhitlik kapasitesini gösterir.",
      "Güncel deprem koşulları (TBDY 2018 çerçevesi) yeni projelerimizin tasarım dilini belirler. Portföyümüzdeki her yapı, aynı güvenlik kültürüne referans oluşturur.",
      "Tokat müteahhit ve Turhal konut arayanlar için Liva Evleri; tamamlanmış, yaşanan bir referanstır.",
      "Detay: /projeler/liva-evleri",
    ],
  },
  {
    slug: "sahika-apartmani-turhal-konut-ticaret",
    title: "Şahika Apartmanı Turhal: Konut ve Ticaret Birlikte, Mevzuata Uygun",
    excerpt:
      "Şahika Apartmanı; 10 daire ve 3 dükkanla Turhal siluetine kazandırıldı. MUFAT özel bina inşaatında deprem ve imar uyumu esas alındı.",
    category: "Projelerimiz",
    tags: ["Şahika Apartmanı", "Turhal inşaat", "Tokat müteahhit", "Konut", "Dükkan"],
    date: "2026-06-18",
    readMin: 6,
    cover: "https://res.cloudinary.com/osgt7obm/image/upload/mufat/projects/sahika-apartmani",
    body: [
      "Şahika Apartmanı’nda konut birimleri ile zemin kat ticaret alanları birlikte projelendirilip inşa edildi. Turhal’da cadde cepheli yapılarda imar çekmeleri, dükkan yüksekliği ve konut mahremiyeti aynı anda çözülmelidir; MUFAT bu dengeyi mevzuata uygun kurar.",
      "Tokat inşaat alıcısı için cephe renkleri ve balkon detayları görünür kaliteyi anlatır; asıl güvence ise ruhsatlı taşıyıcı sistem ve denetlenmiş imalattır. Deprem güvenliği bu güvencenin omurgasıdır.",
      "2026’da Turhal veya Tokat’ta daire / dükkan yatırımı yapanlar, müteahhitin güncel yönetmeliği uygulayıp uygulamadığını sormalıdır. MUFAT cevabı net tutar: yürürlükteki TBDY ve yapı yasalarına uygun üretim.",
      "Proje sayfası: /projeler/sahika-apartmani",
    ],
  },
  {
    slug: "mukavim-konut-kooperatifi-turhal",
    title: "Mukavim Konut Kooperatifi: Turhal’da 45 Daireli Güvenli Teslim",
    excerpt:
      "S.S. Mukavim Konut Yapı Kooperatifi’nde 45 daire; MUFAT ile planlama, imalat ve teslim. Kooperatif inşaatında deprem ve yasal uyum.",
    category: "Projelerimiz",
    tags: ["Kooperatif", "Turhal inşaat", "Tokat müteahhit", "Kat karşılığı", "Konut"],
    date: "2026-06-14",
    readMin: 7,
    cover: "https://res.cloudinary.com/osgt7obm/image/upload/mufat/projects/mukavim-konut",
    body: [
      "Kooperatif konutları Tokat ve Turhal’da yaygın bir modeldir; başarı ise şeffaf süreç ve teknik disipline bağlıdır. Mukavim Konut Yapı Kooperatifi’nde 45 dairelik blok, işveren kooperatif yapısına uygun planlama, imalat ve teslimle tamamlandı.",
      "Tokat müteahhit seçerken kooperatif üyeleri; sözleşme maddelerinin yanında statik proje, zemin etüdü ve iskan yol haritasını da sorgulamalıdır. MUFAT, kat karşılığı ve kooperatif işlerinde aynı mühendislik standardını uygular.",
      "Deprem koşulları 2026’da her zamankinden daha fazla konuşuluyor. Büyük daire sayılı yapılarda taşıyıcı sistem sürekliliği ve imalat kontrolü, can güvenliğinin temelidir.",
      "Turhal inşaat referanslarımız arasında Mukavim; ölçek ve organizasyon kapasitemizi gösteren önemli bir iştir.",
      "Proje: /projeler/mukavim-konut. Kooperatif veya kat karşılığı için iletişime geçin.",
    ],
  },
  {
    slug: "anadolu-lisesi-guclendirme-tokat-deprem",
    title: "Anadolu Lisesi Güçlendirme Tokat: Okul Yapılarında Deprem Güvenliği",
    excerpt:
      "Tokat Anadolu Lisesi güçlendirme işi; eğitim fonksiyonu korunarak deprem güvenliğini artırmaya yönelik imalatlarla tamamlandı.",
    category: "Projelerimiz",
    tags: ["Tokat inşaat", "Güçlendirme", "Deprem", "Okul", "TBDY"],
    date: "2026-06-10",
    readMin: 7,
    cover: "https://res.cloudinary.com/osgt7obm/image/upload/mufat/projects/anadolu-lisesi-guclendirme",
    body: [
      "Okul yapıları, deprem yönetmeliğinde yüksek performans hedefleriyle ele alınır. Tokat’ta Anadolu Lisesi güçlendirme projesinde MUFAT; mevcut binanın deprem güvenliğini artırmaya yönelik imalatları, eğitim fonksiyonunu koruyarak uyguladı.",
      "Tokat inşaat ve güçlendirme işlerinde doğru teşhis (performans analizi) olmadan doğru müdahale olmaz. Güçlendirme; perde ekleme, eleman sargılama veya sistem iyileştirmeleriyle yapısal kapasiteyi yükseltir.",
      "2026 deprem farkındalığında kamu ve eğitim yapıları önceliklidir. MUFAT’ın Turhal merkezli ekibi; Tokat genelinde güçlendirme ve kontrollük hizmetlerinde mevzuata uygun süreç yönetir.",
      "“Tokat müteahhit” araması yapan kurumlar için güçlendirme referansı, konut referansı kadar değerlidir. Bu iş, can güvenliğini doğrudan hedefler.",
      "Proje: /projeler/anadolu-lisesi-guclendirme. Okul / kamu güçlendirme için görüşelim.",
    ],
  },
  {
    slug: "ahmet-dincer-lisesi-turhal-kamu-insaat",
    title: "Ahmet Dinçer Lisesi Turhal: 12 Derslikli Kamu İnşaatı",
    excerpt:
      "Turhal Ahmet Dinçer Lisesi; 12 derslikli okul binası olarak MUFAT ile inşa edildi. Kamu ihale disiplininde deprem ve mevzuat uyumu.",
    category: "Projelerimiz",
    tags: ["Turhal inşaat", "Tokat inşaat", "Kamu ihale", "Okul", "Eğitim"],
    date: "2026-06-06",
    readMin: 6,
    cover: "https://res.cloudinary.com/osgt7obm/image/upload/mufat/projects/ahmet-dincer-lisesi",
    body: [
      "Kamu İhale Kanunu kapsamında okul yapımı; süre, kalite ve mevzuat üçgeninde yürür. Turhal’da 12 derslikli Ahmet Dinçer Lisesi; cephe, derslik düzeni ve dış saha imalatlarıyla eğitim kullanımına uygun teslim edildi.",
      "Tokat ve Turhal’da kamu inşaatı deneyimi, özel sektör müteahhitliğine de disiplin katar. MUFAT; 4734 / 2886 kapsamındaki işlerde sözleşme ve şantiye süreçlerini yasal çerçevede yönetir.",
      "Okul binalarında deprem performansı, konuttan daha yüksek hedeflere bağlanabilir. 2026’da konuşulan deprem koşulları; yeni eğitim yatırımlarında da aynı mühendislik ciddiyetini ister.",
      "Proje özeti: /projeler/ahmet-dincer-lisesi",
    ],
  },
  {
    slug: "mensace-mermer-fabrika-turhal-osb",
    title: "Mensace Mermer Fabrikası: Turhal OSB’de Çelik Fabrika İnşaatı",
    excerpt:
      "1.500 m² Mensace Mermer Sanayi fabrikası; Turhal’da çelik iskeletle inşa edildi. Endüstriyel Tokat inşaatında deprem ve standart uyumu.",
    category: "Projelerimiz",
    tags: ["Turhal inşaat", "Tokat inşaat", "OSB", "Çelik", "Fabrika"],
    date: "2026-06-02",
    readMin: 6,
    cover: "https://res.cloudinary.com/osgt7obm/image/upload/mufat/projects/mensace-mermer-fabrika",
    body: [
      "Mensace Mermer Sanayi için gerçekleştirilen 1.500 m² çelik iskeletli fabrika binası; geniş açıklıklı üretim alanı ve saha hazırlığıyla Turhal’da tamamlandı. OSB / fabrika yapımında MUFAT’ın ölçütü: ilgili standartlar, deprem yönetmeliği ve işveren prosesine uygun teslim.",
      "Tokat inşaat sanayi yatırımlarında çelik konstrüksiyon hız ve açıklık sağlar; bağlantı detayları ve temel sistemi ise deprem davranışını belirler. Bu denge doğru mühendislikle kurulur.",
      "Turhal ve Tokat’ta fabrika yaptıracak sanayiciler için “ucuz çelik” değil, belgelenmiş imalat ve yönetmeliğe uygun proje esastır. 2026 koşullarında bu beklenti daha da yükselmiştir.",
      "Proje: /projeler/mensace-mermer-fabrika. OSB ve fabrika işleri için iletişime geçin.",
    ],
  },
  {
    slug: "turhal-ozel-bina-insaat-muteahhit",
    title: "Turhal Özel Bina İnşaatı: Tokat Müteahhit ile Güvenli Konut",
    excerpt:
      "Turhal’da çok katlı özel konut binası; MUFAT özel bina inşaatıyla kaba işten ince işe teslim. Deprem ve yasalara uygun müteahhitlik.",
    category: "Projelerimiz",
    tags: ["Turhal inşaat", "Tokat müteahhit", "Özel bina", "Konut", "Deprem"],
    date: "2026-05-28",
    readMin: 5,
    cover: "https://res.cloudinary.com/osgt7obm/image/upload/mufat/projects/ozel-bina-2005",
    body: [
      "Özel işveren konutları, Turhal inşaat talebinin önemli kısmını oluşturur. MUFAT’ın tamamladığı çok katlı özel bina örneğinde süreç; kaba inşaattan ince işlere kadar tek elden yönetilerek teslim edildi.",
      "Tokat müteahhit arayan arsa sahipleri için özel bina modeli; kat karşılığına göre daha doğrudan bir sözleşme yapısı sunar. Kritik olan, projenin ruhsatlı ve deprem yönetmeliğine uygun yürütülmesidir.",
      "2026’da geçerli deprem koşulları ve yapı mevzuatı, yeni özel konutlarımızın tasarım ve imalat çerçevesini çizer. Aynı güvenlik kültürü, tüm portföyümüzün ortak paydasıdır.",
      "Turhal veya Tokat’ta özel villa / apartman yatırımı için keşif randevusu alabilirsiniz. Proje örneği: /projeler/ozel-bina-2005",
    ],
  },
];
